name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Check versions
      run: |
        node --version
        npm --version
        
    - name: Install dependencies
      run: |
        cd frontend
        rm -rf node_modules package-lock.json
        npm cache clean --force
        NPM_CONFIG_UPDATE_NOTIFIER=false npm install --legacy-peer-deps --no-audit --no-fund --silent
        
    - name: Verify installation
      run: |
        cd frontend
        npm list --depth=0
        ls -la node_modules/react-scripts/
        cat package.json | grep -A 5 -B 5 "react-scripts"
        echo "Checking for .env files:"
        ls -la .env* || echo "No .env files found"
        
    - name: Setup environment
      run: |
        cd frontend
        if [ ! -f .env.production ]; then
          echo "Creating .env.production from env.production.txt"
          cp env.production.txt .env.production
        fi
        echo "Environment file contents:"
        head -10 .env.production
        
    - name: Clean build directory
      run: |
        cd frontend
        rm -rf build
        
    - name: Check for syntax errors
      run: |
        cd frontend
        echo "Checking for syntax errors..."
        npx eslint src/ --ext .js,.jsx --max-warnings 0 || echo "ESLint found issues but continuing..."
        
    - name: Build
      run: |
        cd frontend
        echo "Starting build process..."
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "Current directory: $(pwd)"
        echo "Contents: $(ls -la)"
        echo "Package.json exists: $(test -f package.json && echo 'YES' || echo 'NO')"
        CI=false GENERATE_SOURCEMAP=false NPM_CONFIG_UPDATE_NOTIFIER=false npm run build
        
    - name: Check build output
      run: |
        cd frontend
        ls -la build/
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/build
