name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Update npm
      run: |
        npm install -g npm@latest
        npm --version
        
    - name: Install dependencies
      run: |
        cd frontend
        rm -rf node_modules package-lock.json
        npm cache clean --force
        npm install --legacy-peer-deps
        
    - name: Verify installation
      run: |
        cd frontend
        npm list --depth=0
        
    - name: Build
      run: |
        cd frontend
        CI=false GENERATE_SOURCEMAP=false npm run build
        
    - name: Check build output
      run: |
        cd frontend
        ls -la build/
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/build
